version: '3.3'

services:
  database:
    image: postgres
    container_name: database-container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres

  frontend:
    image: vbsantos-tcc/frontend:latest
    container_name: frontend-container
    restart: unless-stopped
    ports:
      - "3000:3000"

  backend:
    image: vbsantos-tcc/backend:latest
    container_name: backend-container
    restart: unless-stopped
    ports:
      - "8080:8080"
