version: '2'

services:
  database-tcc:
    image: postgres:13.1-alpine
    container_name: database-tcc
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres

  backend-tcc:
    image: vbsantos-tcc/backend:latest
    container_name: backend-tcc
    restart: unless-stopped
    depends_on:
      - database-tcc
    ports:
      - "8000:8080"
    environment:
      POSTGRES_URL: jdbc:postgresql://database-tcc:5432/postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_HOST: fake-smtp-server-tcc
      EMAIL_PORT: 1025

  frontend-tcc:
    image: vbsantos-tcc/frontend:latest
    container_name: frontend-tcc
    restart: unless-stopped
    depends_on:
      - backend-tcc
    ports:
      - "3000:3000"
    environment:
      API_URL: http://backend-tcc:8000/

  fake-smtp-server-tcc:
    image: maildev/maildev
    container_name: fake-smtp-server-tcc
    restart: unless-stopped
    depends_on:
      - frontend-tcc
    ports:
      - "1025:1025"
      - "1080:1080"
